### PR TITLE
Microverse > Project BookStore > Milestone 5 > FB Styles

### PR DESCRIPTION
**Pull request by jurgen1c**
## In this branch we:

- Added navbar 
- Added styles for form, book list & navbar
- Refactor jsx to match styles

### CODE REVIEW

**Review by bellom — CHANGES_REQUESTED** [review]
## Hi Team :clap: 

### Awesome job so far!! :+1: 

# Status: Changes Required! ♻️ 

I think you guys missed the project specification section, we need to make sure your design looks exactly the same just like the provided design in the pathwright.

Screenshot from your app;
image


Kindly take a step back to double-check.
image

[check out project specific in Pathwright](https://microverse.pathwright.com/library/react-redux-v11/184438/path/step/106376032/l)



### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

**Comment by jurgen1c** [comment]
home

# Note:
- Project is fully styled in branch fb-styles as can be seen in attached image or read me. Perhaps wrong branch was checked.

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
# Changes Requested 💀 

Thank You for submitting this project. 

- [ ] Please check the live link of your project. Styling is not being uploaded. 
Please work on it and request another review. 

Best,
Arslan Bisharat
slack; arslanbisharat

**Comment by jurgen1c** [comment]
- Branch fb-styles now deployed to live link.

**Comment by arslanbisharat** [comment]
> # Changes Requested 💀
> Thank You for submitting this project.
> 
> * [ ]  Please check the live link of your project. Styling is not being uploaded.
>   Please work on it and request another review.
> 
> Best,
> Arslan Bisharat
> slack; arslanbisharat

As I requested earlier, styling is not being uploaded. Please work on it before requesting a Code Review

109580933-bbbc6c80-7afb-11eb-9ebf-c25f0dcb092f

**Comment by jurgen1c** [comment]
### For video presentation of project and live demo click [here](https://www.loom.com/share/0766aca64b214648ac7a1be4e8f6686c)

- [Live Demo](https://bookstore-jcg-oyc.herokuapp.com/)

**Review by mikenath223 — APPROVED** [review]
### CONGRATULATIONS  👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

**Pull request merged**
